version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/app
  redis:
    image: redis:7
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: